### ISSUE TITLE
Calculation of frequencies associated with each mode

### ISSUE THREAD

**Issue by purvi24** [reuter-group/webnma3#2]
Dear,

I am trying to calculate the frequency associated with each mode using the eigen values using the formula:
Frequency. = sqrt(EigenValue) 
However, the values obtained doesn't correlate well with the literature. I suspect there is an issue with the unit conversions. Could somebody assist me with exactly how to obtain the absolute frequency values? 

Greetings,
Purvi Gupta

**Comment by Ginko-X** [comment]
Hi Purvi,
Sorry for the late reply. As I mentioned in the email, the frequency can be calculated as 
<img src="https://render.githubusercontent.com/render/math?math=\Large f={\sqrt{e}} \over {2\pi}"> 
where _e_ is the eigenvaule in the `modes.txt` file, and _f_  the vibrational frequencies. 

In addition, the transformation between the raw modes `v` (in the `modes.txt` file) and the vibrational modes  `V` is:
<img src="https://render.githubusercontent.com/render/math?math=\Large V=v \over \sqrt{M} \times {\sqrt{2kT}} \over  {2\pi f}">
where _M_ is the protein's mass, _k_ is constant (=1.3806513e-23 * 6.0221367e23 / 1000), and _T_ is the temperature (=300).

I didn't find this calculation detail from WEBnma's publications, but you may find more from Konrad Hinsen's work and the source code of [MMTK](https://github.com/khinsen/MMTK) (earlier versions of WEBnma used MMTK to calculate the normal modes):

> Hinsen, Konrad. "Normal mode theory and harmonic potential approximations." Normal Mode Analysis. Chapman and Hall/CRC, 2005. 25-40.

> Hinsen, Konrad. "Analysis of domain motions by approximate normal mode calculations." Proteins: Structure, Function, and Bioinformatics 33.3 (1998): 417-429.

I hope this helps, and feel free to ask if you have further questions.

**Comment by Ginko-X** [comment]
As no further question posted I just close this issue.
