### ISSUE TITLE
Problems with running WebNMA and outputs

### ISSUE THREAD

**Issue by Bhawnadixit3** [reuter-group/webnma3#6]
Dear admin,
I am running WebNMA for an Alphafold  model (roughly 2700 residues), and it failed both remotely and on the webserver by aborting the job. 
1) I would like to know is there a limit on number of residues? Can webNMA handle a structure over 2000 residues?

For other results:
2) In webNMA outputs, the results contain two files for eigenvalues (modes.txt), and '/displacement/eigen.txt', when I plot them together, they are not same, I would like to know how do you calculate eigen.txt as they seem to have some constant and why?

3) What are the physical units of eigenvalues in both cases, according to the force constant given in the WebNMA reference from 2014 .

**Comment by Ginko-X** [comment]
Hi, 
1. webNMA can process up to 20000 residues, so this job failure may be due to other reasons (usually invalid/unsupported PDB format)
2. the visualized eigenvaules in `eigen.txt` is vibrational frequency, converted by a formula mentioned here https://github.com/reuter-group/webnma3/issues/2#issuecomment-974027584
3. for this question sorry I can't give you quick answer, you may refer to the comment/references I mentioned above in Answer 2, or ask the project leader Professor Nathalie Reuter

**Comment by phillippesamer** [comment]
Dear @Bhawnadixit3,

We are in the middle of a team transition, which led to in a long time to follow up your question here. We are sorry, and hope that our previous answer clarified your questions.

**Comment by Bhawnadixit3** [comment]
Dear Phillipe and Dandan,
I would like to thank you for the previous reply. I wrote a reply, however, I forgot to press send.

I'm currently in the process of analyzing the WebNMA outputs for my protein study, and I wanted to share some observations with you. I ran my protein on both WebNMA and elNemo, to cross-verify the results. Interestingly, both tools produced a similar error message, indicating that the first six zero modes are not close to 0. Also, elNemo produced the error, “there is low collectivity among the first five modes”. I suspect that this issue might be due to the need for energy minimization. So, I decided to discard the model from my dataset.

Moreover, I would like to suggest that in the future, it would be useful if the documentation or descriptions of parameters, such as "rawmodes_to_vibrational," could include information about their physical units and the expected output units or specify when a parameter represents a unitless measure. This clarification would increase the usability and interpretability of the results.

It took me several days after I reviewed the code and related literature in-depth to get a clear picture.  However, it was not straightforward. I hope future updates or resources will address this concern.

Kind regards,
Bhawna Dixit
________________________________

**Comment by phillippesamer** [comment]
Dear Bhawna,

Thanks for your thorough work in using (and understanding!) WEBnma. 

Your concern about the first six modes should be clear now, and you should really disregard them in the analyses! And you raised a good point about making the units clearer, which we'll try to address in the next release.

I am closing the issue, hoping that we're finally on the same page! Do let us know if there's something else! (:

Kind regards,
Phillippe

**Comment by phillippesamer** [comment]
Dear Bhawna,

Thanks for your thorough work in using (and understanding!) WEBnma.

Your concern about the first six modes should be clear now, and you should really disregard them in the analyses! And you raised a good point about making the units clearer, which we'll try to address in the next release.

I am closing the issue, hoping that we're finally on the same page! Do let us know if there's something else! (:

Kind regards,
Phillippe
