### ISSUE TITLE
Job run status 

### ISSUE THREAD

**Issue by vshree23** [reuter-group/webnma3#7]
Hi Team,

I have given some runs in webnma. In the last 3 days, the status of runs is - waiting in queue, and no progress is seen. Could you let us know what the issue is?

Thanks,
Vandana

**Comment by Ginko-X** [comment]
Hi Vandana,

Please contact Prof. Nathalie [Nathalie.Reuter@uib.no](mailto:Nathalie.Reuter@uib.no) for this service issue. 

Best,
Dandan

**Comment by vshree23** [comment]
Sure, thanks for letting me know

**Comment by phillippesamer** [comment]
Dear Vandana,

We are in the middle of a team transition, which led to in a long time to follow up your question here. We are sorry, and hope that you had success in your job runs.

Best,
Phillippe

**Comment by phillippesamer** [comment]
I am closing the issue, but feel free to reach us again.

**Comment by phillippesamer** [comment]
I am closing the issue, but feel free to reach us if there is something else..! (:
